login/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
from app_login.views import main, signup
from userprofile.views import TodoList, TodoDetail, TodoCreate, TodoDelete, TodoUpdate, listar

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'login.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'app_login.views.main', name='main'),
    url(r'^signup$', 'app_login.views.signup', name='signup'),
    url(r'^signup$', 'app_login.views.signup', name='signup'),
    url(r'^login$', login, {'template_name': 'login.html', }, name="login"),
    url(r'^home$', 'app_login.views.home', name='home'),
    url(r'^logout$', logout, {'template_name': 'main.html', }, name="logout"),

    url(r'^$', 'userprofile.views.ingresar', name='ingresar'),
    url(r'^index$', TodoList.as_view(), name='app_list'),
    url(r'^Todo(?P<pk>\d+)$', TodoDetail.as_view(), name='app_detail'),
    url(r'^New$', TodoCreate.as_view(), name='app_create'),
    url(r'^Todo(?P<pk>\d+)/Update$', TodoUpdate.as_view(), name='app_update'),
    url(r'^Todo(?P<pk>\d+)/Delete$', TodoDelete.as_view(), name='app_delete'),
    url(r'^listar/todo$', 'userprofile.views.listar'),
    

)

app_login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User


class Todo(models.Model):
    PRIORITY_LIST = (
        (0, 'DNI'),
        (5, 'PARTIDA'),
        (10, 'MILITAR'),
        (15, 'RUC'),
    )
    departamento = models.CharField(max_length=40)  #tiltle
    usuario = models.ForeignKey(User) #owner
    documento = models.PositiveSmallIntegerField(choices=PRIORITY_LIST, default=5)#prioryti
    added_on = models.DateTimeField(auto_now_add=True)
    fecha = models.DateField()#due on
    
    class Meta:
        permissions = (
            ('list_app', 'Can view list ap'),
            ('view_app', 'Can view ap'),
            ('add_app', 'Can add ap'),
            ('change_app', 'Can change ap'),
            ('delete_app', 'Can delete ap'),
        )
        ordering = ['fecha']
    def __unicode__(self):
        return u"%s" % self.usuario
    @models.permalink
    def get_absolute_url(self):
        return ('app_detail', [int(self.pk)])

app_login/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm


class SignUpForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email', 'first_name', 'last_name', ]
        widgets = {
                    'password': forms.PasswordInput(),
                }

userprofile/forms.py
from django import forms
from userprofile.models import Todo

class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ('departamento', 'usuario', 'documento', 'fecha', )

app_login/views.py
from django.shortcuts import render, render_to_response
from django.contrib.auth.models import User
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.http.response import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from app_login.forms import SignUpForm


def main(request):
    return render_to_response('main.html', {}, context_instance=RequestContext(request))
def signup(request):
    if request.method == 'POST':  # If the form has been submitted...
        form = SignUpForm(request.POST)  # A form bound to the POST data
        if form.is_valid():  # All validation rules pass
            # Process the data in form.cleaned_data
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            email = form.cleaned_data["email"]
            first_name = form.cleaned_data["first_name"]#first_name
            last_name = form.cleaned_data["last_name"]#dlast_name
            

            # At this point, user is a User object that has already been saved
            # to the database. You can continue to change its attributes
            # if you want to change other fields.
            user = User.objects.create_user(username, email, password)
            user.first_name = first_name
            user.last_name = last_name

            # Save new user attributes
            user.save()
            return HttpResponseRedirect(reverse('main'))  # Redirect after POST
    else:
        form = SignUpForm()
    data = {
        'form': form,
    }
    return render_to_response('signup.html', data, context_instance=RequestContext(request))

@login_required()
def home(request):
    return render_to_response('home.html', {'user': request.user}, context_instance=RequestContext(request))

userprofile/views.py
from django.views.generic.list import ListView
from userprofile.models import Todo
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from userprofile.forms import TodoForm
from django.shortcuts import redirect, render, render_to_response, get_object_or_404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator

from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


@method_decorator(permission_required('app.list_app'))
def listar(request):
    porhacer = Todo.objects.all()
    return render(request, 'app/listar.html', {'porhacer':porhacer})

class TodoList(ListView):
    model = Todo

class TodoDetail(DetailView):
    model = Todo
    @method_decorator(permission_required('app.view_app'))
    def dispatch(self, *args, **kwargs):
        return super(TodoDetail, self).dispatch(*args, **kwargs)

class TodoCreate(CreateView):
    model = Todo
    form_class = TodoForm
    @method_decorator(permission_required('app.add_app'))
    def dispatch(self, *args, **kwargs):
        return super(TodoCreate, self).dispatch(*args, **kwargs)
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()
        return redirect(self.object)

class TodoUpdate(UpdateView):
    model = Todo
    form_class = TodoForm
    @method_decorator(permission_required('app.change_app'))
    def dispatch(self, *args, **kwargs):
        return super(TodoUpdate, self).dispatch(*args, **kwargs)

class TodoDelete(DeleteView):
    model = Todo
    @method_decorator(permission_required('app.delete_app'))
    def dispatch(self, *args, **kwargs):
        return super(TodoDelete, self).dispatch(*args, **kwargs)
    def get_success_url(self):
        # To do this because the success_url class variable isn't reversed...
        return reverse('app_list')



#################################################
def ingresar(request):
    if not request.user.is_anonymous():
        return HttpResponseRedirect('/index')
    if request.method == 'POST':
        formulario = AuthenticationForm(request.POST)
        if formulario.is_valid:
            usuario = request.POST['username']
            clave = request.POST['password']
            acceso = authenticate(username=usuario, password=clave)
            if acceso is not None:
                if acceso.is_active:
                    login(request, acceso)
                    return HttpResponseRedirect('/')
                else:
                    return render_to_response('nome.html',
                                              context_instance=RequestContext(request))
            else:
                return render_to_response('nome.html',
                                          context_instance=RequestContext(request))
    else:
        formulario = AuthenticationForm()
    return render_to_response('login.html', {'formulario': formulario},
                              context_instance=RequestContext(request))
@login_required(login_url='/ingresar')
def privado(request):
    usuario = request.user
    return render_to_response('anonymus.html', {'usuario': usuario},
                              context_instance=RequestContext(request))

@login_required(login_url='/ingresar')
def cerrar(request):
    logout(request)
    return HttpResponseRedirect('/')

templates/base.html
<html>
    <head>

    <title>{% block title %}Untitled{% endblock %} | Todo list with permissions</title>
</head>
<body>
<div class = "container">
    <div class="alert alert-info">
        <h1>Examen de lenguaje de programacion 2</h1>
            <h2>Bill Edgar Canaza Chani</h2>

        <img src="fc,140x140,creme.u5" class="img-polaroid">

        <span class="input-group-addon"><span class="glyphicon
                glyphicon-globe"></span>Hola Mundo Cruel</span>
    </div>
        <a href="{% url 'logout' %}">Salir</a>

        <a type="button" class="btn btn-info" href="{% url 'app_list' %}">Inicio</a>{% if perms.todo.add_todo %}   
        <a type="button" class="btn btn-info" href="{% url 'app_create' %}">Agregar Usuario</a>{% endif %}

        {% if user.is_authenticated %}
           <p class="navbar-text pull-right">    
               <strong>Usuario {{user.username}}</strong>
               
        <span class="glyphicon glyphicon-user"></span> 
           </p>
           {% endif %} 





    <div class =  "well">         
{% block content %}
The end user should never ever see this!
{% endblock %} 
    </div>
</div>
 
        </div> 
</body>
</html>

templates/home.html
  <tr>REGISTRO DE DATOS DEL USUARIO: " <td>{{ user.username }}</td>"<hr style="color: #0056b2;" />
 <table><th>Nombre :</th>  
        <tr>
            <td>{{ user.username.label_tag }}</td>
            <td>{{ user.username }}</td>

        </tr>
       
        <th>Email :</th>              
        <tr>
            <td>{{ user.email.label_tag }}</td>
            <td>{{ user.email }}</td>
        </tr>
        <th>DNI :</th>
        <tr>
            <td>{{ user.first_name.label_tag }}</td>
            <td>{{ user.first_name }}</td>
        </tr>
        <th>provincia :</th>
         <tr>
            <td>{{ user.last_name.label_tag }}</td>
            <td>{{ user.last_name }}</td>
        </tr>
        <th>Hora De Ingreso :</th>
        <tr>
            <td>{{ user.date_joined.label_tag }}</td>
            <td>{{ user.date_joined }}</td>
        </tr>
        <th>Hora Despues de Ingreso :</th>
        <tr>
            <td>{{ user.last_login.label_tag }}</td>
            <td>{{ user.last_login }}</td>
        </tr>
    
 
    </table>
 
    <a href="{% url 'logout' %}">Salir</a>
    <li><a href="{% url 'app_list' %}">index</a></li>

    
 

templates/login.html
 {% if form.errors %}

        <h1>INTENTE NUEVAMENTE</h1>
        
    {% endif %}
 
    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
        {% csrf_token %}
        <table>
            <tr>
                <th>Usuario :</th><td>{{form.username}}</td>
            </tr>
           
             <tr>
                <th>Contraseña :</th><td>{{form.password}}</td>
            </tr>
        </table>
 
        <input type="submit" value="INGRESAR"/> <input type="hidden" name="next"
                                                    value="{{ next }}"/>
    </form>

templates/main.html
<h1>Login Bill-Edgar</h1>
<h2>Lp2</h2>


 
        <a href="{% url 'signup' %}">Sign Up</a>
        <a href="{% url 'login' %}">Login</a>
         

templates/signup.html
  {% if form.errors %}
        <p>{{ form.errors }}</p>
    {% endif %}
 
    <form method="post" action="{% url 'signup' %}">
 
        {% csrf_token %}
 
        <table>
           <tr>
                <th>Usuario :</th><td>{{form.username}}</td>
            </tr>
           
             <tr>
                <th>Contraseña :</th><td>{{form.password}}</td>
            </tr>

             <tr>
                <th>{{ form.email.label_tag }}</th>
                <td>{{ form.email }}</td>
            </tr>
 
            <tr>
                <th>Documento :</th><td>{{form.first_name}}</td>
            </tr>
 
            <tr>
                <th>Departamento :</th><td>{{form.last_name}}</td>
            </tr>
 
        </table>
 
        <input type="submit" value="Ingresar"/>
    </form>

templates/userprofile/app_detail.html
{% extends 'userprofile/base.html' %}

{% block title %}{{todo}}{% endblock %}

{% block content %}
<table>
<tr><th>departamento:</th><td>{{todo}}</td></tr>
<tr><th>usuario:</th><td>{{todo.usuario}}</td></tr>
<tr><th>documento:</th><td>{{todo.get_documento_display}}</td></tr>
<tr><th>Added on:</th><td>{{todo.added_on}}</td></tr>

<tr><th>fecha:</th><td>{{todo.fecha}}</td></tr>
</table>
{% if perms.userprofile.change_app %}
<a href="{% url 'app_update' todo.pk %}">Update</a>
{% endif %} | {% if perms.userprofile.delete_app %}
<a href="{% url 'app_delete' todo.pk %}">Delete</a>
{% endif %}
{% endblock %}

templates/userprofile/base.html
{% extends 'base.html' %}
<html>
<head>
  <title>{% block title %}Untitled{% endblock %} | Todo list with permissions</title>
  
</head>
<body>
<h1>EXAMEN LP2 Registro Usuarios</h1>
<li><a href="{% url 'app_list' %}">REGISTRO</a></li>
{% if perms.userprofile.add_app %}
<li><a href="{% url 'app_create' %}">AGREGAR</a></li>
{% endif %}
<hr/>
{% block content %}
The end user should never ever see this!
{% endblock %}
</body>
</html>

templates/userprofile/listar.html
{% extends 'userprofile/base.html' %}

{% block title %}{{todo}}{% endblock %}

{% block content %}
<ul>
{% for item in porhacer %}

    <li>{{ item }}</li>

{% endfor %}

</ul>
{% endblock %}

templates/userprofile/todo_confirm_delete.html
{% extends 'userprofile/base.html' %}
{% load url from future %}

{% block title %}{{object_name}} Confirm delete?{% endblock %}

{% block content %}
<h3>esta seguro de eliminar {{object}}?</h3>
<form action="" method="post">{% csrf_token %}
<input type="submit" value="acepto"/>  <input type="button" value="Cancel" onclick="window.history.go(-1);"/>
</form>
{% endblock %}

templates/userprofile/todo_detail.html
{% extends 'userprofile/base.html' %}

{% block title %}{{todo}}{% endblock %}

{% block content %}
<table>
<tr><th>departamento:</th><td>{{todo.departamento}}</td></tr>
<tr><th>usuario:</th><td>{{todo.usuario}}</td></tr>
<tr><th>documento:</th><td>{{todo.get_documento_display}}</td></tr>
<tr><th>Added on:</th><td>{{todo.added_on}}</td></tr>
<tr><th>fecha:</th><td>{{todo.fecha}}</td></tr>

</table>
{% if perms.userprofile.change_app %}
<a href="{% url 'app_update' todo.pk %}">Update</a>
{% endif %} | {% if perms.userprofile.delete_app %}
<a href="{% url 'app_delete' todo.pk %}">Delete</a>
{% endif %}
{% endblock %}

templates/userprofile/todo_form.html
{% extends 'userprofile/base.html' %}
{% load url from future %}

{% block title %}Todo Form{% endblock %}

{% block content %}
<h3>{% if object %}Updating {{object}}{% else %}Add a new Todo{% endif %}</h3>
<form action="" method="post">{% csrf_token %}
<table>
{{form}}
</table>
<input type="submit" value="GUARDAR"/></form>
{% endblock %}

templates/userprofile/todo_list.html
{% extends 'userprofile/base.html' %}

{% block title %}Todo List{% endblock %}

{% block content %}
<table class = "table table-striped" cellspacing = '0'> 
<thead><tr><th>Users</th><th>Acciones</th></tr></thead>
<tbody>
  {% for todo in todo_list %}
  <tr><td>{% if perms.todo.view_todo %}<a 
  	          href="{{userprofile.get_absolute_url}}">{{todo}}</a>{% else %}{{todo}}{% endif %}</td>
  <td>{% if perms.userprofile.change_todo %}<a href="{% url 'app_update' todo.pk %}">Editar</a>{% endif %} | {% if perms.userprofile.delete_app %}<a href="{% url 'app_delete' todo.pk %}">Eliminar</a>{% endif %}</td></tr>
  {% endfor %}
</tbody>
</table>
{% endblock %}